import random
from twitchio.ext import commands


class CookieComponent(commands.Component):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name="galletita")
    async def galletita(self, ctx: commands.Context) -> None:
        user = ctx.author.name

        messages = [
            f"{user}, si el mundo fuera un repo, tú serías el merge conflict que nadie quiere resolver.",
            f"{user}, hoy es el día perfecto para escribir el código que cambiará el futuro… o al menos para romper algo.",
            f"{user}, recuerda: incluso un error 500 puede ser una oportunidad para aprender.",
            f"{user}, las estrellas se alinean, pero tu código sigue dando error. Al menos no estás solo en el debugging.",
            f"{user}, la suerte está de tu lado, pero el destino todavía no ha aprobado tu pull request.",
            f"{user}, el canal está lleno de héroes, pero hoy te toca ser el villano. ¡La tragedia está a la vuelta de la esquina!",
            f"{user}, aunque hoy no sea tu mejor día, recuerda que incluso un bug es una oportunidad para mejorar.",
            f"{user}, las galletitas de la fortuna predicen tu futuro… o al menos tu próximo fallo de compilación.",
            f"{user}, el universo está lleno de bugs, pero no te preocupes, tu comunidad siempre te apoyará.",
            f"{user}, hoy será el día en que todo saldrá mal, pero con un poco de suerte, al menos aprenderás algo.",
            f"{user}, si el código de tu vida fuera un repo, hoy tendrías un 'merge conflict' épico.",
            f"{user}, las galletitas nunca mienten. Si te sale una mala, es porque tu código también tiene errores.",
            f"{user}, a veces la vida te da código que no compila. Pero no te preocupes, siempre puedes hacer un 'git revert'.",
            f"{user}, el camino de la vida no es fácil, pero al menos siempre puedes hacer un 'git stash' para huir temporalmente.",
            f"{user}, un buen código no tiene errores, pero si los tiene, al menos puedes culpar a tu compilador.",
            f"{user}, Reactnecita te observa, pero eso no garantiza que tu código funcione hoy.",
            f"{user}, no importa cuántas veces falles, recuerda que el mundo necesita más desarrolladores con tu capacidad para romper todo.",
            f"{user}, como buen dev, tu destino está sellado. Los bugs te siguen como si fueras un paréntesis olvidado.",
            f"{user}, las estrellas pueden estar alineadas, pero tu código probablemente todavía tenga un error 'undefined'.",
            f"{user}, hoy es el día perfecto para iniciar ese proyecto… o para romperlo por completo.",
            f"{user}, en este canal, el código siempre tiene bugs, pero tus amigos están aquí para ayudarte a depurarlos.",
            f"{user}, la vida te da 'breakpoints' en los momentos menos esperados. Prepárate para depurar tu destino.",
            f"{user}, si el código fuera tu vida, hoy estarías haciendo un 'git reset' de todas tus decisiones.",
            f"{user}, los grandes desarrolladores aprenden de sus errores, pero hoy parece que todos tus errores están aprendiendo de ti.",
            f"{user}, la comunidad te saluda, pero tu código sigue sin compilar. ¡Sigue intentándolo!",
            f"{user}, en un mundo lleno de 'commits', hoy parece que tu código está en un 'merge conflict' eterno.",
            f"{user}, todo está perdido. Pero hey, al menos los logs del sistema pueden contarte lo que hiciste mal.",
            f"{user}, el futuro está lleno de oportunidades, pero hoy probablemente está lleno de bugs también.",
            f"{user}, a veces el camino al éxito es una larga serie de commits fallidos. ¡Hoy estás justo en el medio de eso!",
            f"{user}, si alguna vez te sientes perdido, recuerda que hasta el mejor desarrollador tiene que depurar.",
            f"{user}, hoy no habrá suerte, solo trabajo duro… y muchas horas de debugging.",
            f"{user}, si tu código pudiera hablar, estaría diciendo '¡Ayúdame, por favor!'",
            f"{user}, en el canal de Pythonesa, hasta los errores se celebran. ¡Hoy será un día lleno de aprendizaje!",
            f"{user}, los bugs son solo parte del proceso… y hoy tienes más bugs que una fábrica de errores.",
            f"{user}, a veces la vida te da bugs, y a veces te da todo un 'stack trace' de problemas.",
            f"{user}, el universo tiene un plan para ti, pero tu código tiene un error 404.",
            f"{user}, las malas decisiones también son decisiones. Hoy tu código es un 'fail' épico, pero al menos tienes la oportunidad de mejorar.",
            f"{user}, recuerda que incluso el mejor código a veces necesita un poco de ayuda externa. ¡Hoy es tu día de pedir auxilio!",
            f"{user}, no todo en la vida es un 'git push', también hay momentos de 'git pull' cuando necesitas retroceder.",
            f"{user}, tu código tiene más errores que un servidor en producción sin backups. ¡A por el refactor!",
            f"{user}, la suerte no está de tu lado hoy, pero siempre puedes culpar a la red por el fallo.",
            f"{user}, si tu vida fuera un repo, estarías haciendo un 'git fetch' sin cambios.",
            f"{user}, hoy es un buen día para aprender de tus errores. Pero también es un buen día para que tu código no compile.",
            f"{user}, el canal de Pythonesa es como un sistema en producción: siempre en constante actualización, pero con bugs imprevistos.",
            f"{user}, la suerte está de tu lado, pero tu código probablemente esté en un bucle infinito.",
            f"{user}, la vida es como un código: llena de incertidumbres, pero con la esperanza de un buen resultado.",
            f"{user}, hoy no tienes suerte, pero tienes un buen equipo. ¡Juntos resolverán esos bugs!",
            f"{user}, no te preocupes, incluso los mejores desarrolladores tienen sus días malos. ¡Hoy es solo uno más en el camino!",
            f"{user}, las malas decisiones son solo pasos hacia el éxito… aunque hoy te haya tocado dar un paso atrás.",
            f"{user}, a veces la vida es como un 'git clone': copia todo, pero nunca sabes qué errores traerá.",
            f"{user}, tu código es tan épico que los errores se sienten honrados de estar en él.",
            f"{user}, si alguna vez te sientes perdido, recuerda que el canal de Pythonesa siempre tiene un comando de ayuda.",
            f"{user}, el destino te ha dado una oportunidad, pero tu código probablemente la haya bloqueado con un error 403.",
            f"{user}, hoy es un buen día para ser un héroe o para causar un buen desastre. ¡Tú decides!",
            f"{user}, el código está lleno de bugs, pero tu comunidad está aquí para ayudarte a depurarlos.",
            f"{user}, la vida es como un 'commit': a veces, solo necesitas hacer un 'git reset' y empezar de nuevo.",
            f"{user}, en este canal, hasta los errores más grandes tienen un propósito: enseñarte a ser más fuerte.",
            f"{user}, la vida es como un repo: llena de commits, pero también llena de conflictos.",
            f"{user}, las galletitas no siempre traen buenas noticias, pero tu código siempre tiene una solución.",
            f"{user}, no todos los días son buenos, pero al menos siempre hay algo que aprender de un error de compilación.",
            f"{user}, hoy será un día de reflexión y mejoras. O un día de caos total. ¡Quién sabe!",
            f"{user}, el código que escribes hoy podría ser legendario. O podría ser un bug interminable. ¡Descúbrelo!",
            f"{user}, el universo tiene sus altibajos, pero tu código probablemente tiene más bajadas que subidas.",
            f"{user}, los héroes no nacen con habilidades perfectas, pero tú naciste para depurar el caos.",
            f"{user}, cada error es una oportunidad para mejorar. Hoy, probablemente, sea tu oportunidad de aprender a fondo.",
            f"{user}, no todos los días son de fortuna, pero todos los días son una oportunidad para mejorar el código de tu vida.",
            f"{user}, las galletas son solo un recordatorio de que a veces las cosas no salen como las planeas.",
            f"{user}, el futuro está lleno de bugs, pero también de oportunidades para ser mejor.",
            f"{user}, recuerda: si la vida fuera un código, hoy te habría tocado un 'git reset'.",
            f"{user}, un buen desarrollador sabe cuándo pedir ayuda. Hoy parece ser uno de esos días.",
            f"{user}, los errores son solo 'bugs' en tu historia. ¡Aplícales el 'debug' y sigue adelante!",
            f"{user}, en el canal de Pythonesa, todos los bugs son bienvenidos, pero los errores son siempre un paso hacia el éxito.",
            f"{user}, la suerte te sonríe, pero hoy parece que tu código solo tiene errores de sintaxis.",
            f"{user}, el camino del desarrollador está lleno de incertidumbres, pero siempre tienes la fuerza de tu comunidad.",
            f"{user}, el mundo puede ser un lugar caótico, pero al menos en este canal hay un comando para todo.",
            f"{user}, si el código fuera tu vida, hoy estarías en una constante lucha con un 'merge conflict'.",
            f"{user}, los días malos son solo oportunidades para mejorar. ¡Recuerda que tu código siempre tiene margen de mejora!",
            f"{user}, las malas decisiones no te definen, pero definitivamente tus commits sí.",
            f"{user}, aunque no tengas suerte hoy, al menos tienes un equipo que te respalda.",
            f"{user}, hoy no es tu día, pero al menos hay muchas galletitas de la fortuna esperando a cambiar eso.",
            f"{user}, la vida no siempre es un código limpio, pero siempre tiene una solución. Al menos hasta que encuentres el error 500.",
            f"{user}, hoy es el día perfecto para ser tan épico como Hardy ganando en carritos. ¿Te atreves?",
            f"{user}, el destino no tiene bugs, pero tu historia está llena de 'features' inesperadas.",
            f"{user}, como un buen 'commit', cada decisión que tomas marca el estado de tu vida.",
            f"{user}, el canal de Pythonesa es como un repo: lleno de ramas, pero tú eres la fusión que todos esperaban.",
            f"{user}, en este canal, los errores se transforman en éxitos. ¡Eres parte de nuestra comunidad de depuradores de sueños!",
            f"{user}, si alguna vez te sientes perdido, recuerda que incluso el código más complejo tiene un lugar en nuestro repositorio de ideas.",
            f"{user}, en tu vida hay más potencial que en un pull request aprobado por Hardy. ¡Aprovecha este momento!",
            f"{user}, las estrellas del canal de Pythonesa están alineadas hoy, y tu código de vida está listo para brillar.",
            f"{user}, como el mejor código de producción, eres imparable. Nadie puede detenerte, ni siquiera un bug de última hora.",
            f"{user}, la comunidad de Pythonesa te observa con admiración. Estás a punto de hacer un merge épico con tu futuro.",
            f"{user}, tu viaje en la vida está lleno de commits de valor, pero recuerda siempre dejar un mensaje épico en cada uno.",
            f"{user}, las oportunidades son como un buen pull request. Si las dejas pasar, alguien más lo hará.",
            f"{user}, todo lo que necesitas para ser un verdadero 'dev-picante' ya lo tienes dentro de ti. ¡Es momento de compilar tu éxito!",
            f"{user}, el canal de Pythonesa te guía como un sistema de logs, nunca dejes de escribir tu historia.",
            f"{user}, como Hardy en Smash Karts, hoy es tu día para acelerar. ¡Atrévete a tomar esa curva!",
            f"{user}, un buen mod como ChrisVDev nunca te dejaría caer en la trampa de la procrastinación. ¡Vamos, levántate y hazlo!",
            f"{user}, tu futuro es como un repo: nunca sabes qué increíble característica va a surgir después de un buen refactor.",
            f"{user}, si alguna vez dudas, recuerda que hasta el mejor código necesita un debug, y nosotros te respaldamos como siempre.",
            f"{user}, las galletitas de la fortuna son solo el principio. Estás a punto de desbloquear nuevas ramas en tu vida.",
            f"{user}, el canal de Pythonesa tiene más potencial que una infraestructura de hosting montada por la comunidad.",
            f"{user}, como un buen stack trace, siempre sabes dónde ir cuando las cosas se complican.",
            f"{user}, hoy, como Hardy, eres el rey del juego. Pero recuerda, solo el verdadero dev sabe cuándo hacer un rollback.",
            f"{user}, el destino está en tu código, y la comunidad está lista para celebrarlo.",
            f"{user}, el único bug que necesitas hoy es el que te llevará directo al éxito.",
            f"{user}, cada paso en tu vida es como un commit en la historia de este canal. ¡Haz que cuente!",
            f"{user}, en un mundo lleno de código inestable, tú eres la constante que todos necesitan.",
            f"{user}, si tus sueños fueran líneas de código, hoy estarías haciendo un push al servidor de tus logros.",
            f"{user}, cuando el código de tu vida se compile, saldrá un resultado épico, tal como lo haría cualquier pull request aprobado en el canal.",
            f"{user}, como el mejor código de producción, tus decisiones no tienen margen de error. ¡Cada una es una lección valiosa!",
            f"{user}, los errores solo son lecciones disfrazadas. Hoy es un buen día para aprender algo nuevo.",
            f"{user}, recuerda que en el canal de Pythonesa, no hay errores, solo nuevos caminos para aprender y mejorar.",
            f"{user}, la comunidad te sigue como si fueras el mejor dev del canal. ¡Este es tu momento para brillar!",
            f"{user}, si el código de tu vida no funciona, solo recuerda: siempre puedes hacer un 'git revert'. ¡Nunca es tarde para empezar de nuevo!",
            f"{user}, en la vida como en el código: cada error se convierte en una oportunidad para mejorar. ¡Vamos por esa versión estable!",
            f"{user}, hoy el canal está en modo épico. ¿Estás listo para compilar tu mejor versión?",
            f"{user}, si alguna vez dudas de tu poder, recuerda: un buen commit no solo es para tu código, también es para tu futuro.",
            f"{user}, las galletitas no te dirán tu destino, pero tu código sí lo hará. ¡Sigue escribiendo tu historia!",
            f"{user}, la comunidad de Pythonesa está lista para celebrarte como el mejor pull request. ¡Hazlo épico!",
            f"{user}, el canal te mira como el héroe de este código. ¡No dudes, sigue adelante!",
            f"{user}, cada línea de código que escribes, es una línea más cerca de tu éxito.",
            f"{user}, la suerte está de tu lado, pero no te confíes demasiado.",
            f"{user}, no todo lo que brilla es oro, pero hoy tendrás un día dorado.",
            f"{user}, el camino al éxito tiene muchas curvas, pero tú sabes cómo manejarlas.",
            f"{user}, si alguien te dice que no puedes, demuéstrales que sí puedes.",
            f"{user}, hoy será un buen día para tomar decisiones impulsivas. ¡A por ello!",
            f"{user}, ¿por qué esperar al futuro cuando puedes conquistar el presente?",
            f"{user}, no busques la perfección, busca lo épico.",
            f"{user}, cuando dudes, recuerda: el universo conspira a tu favor… o no.",
            f"{user}, hoy la suerte te sonríe, pero no dejes que se escape sin aprovecharla.",
            f"{user}, la respuesta estaba dentro de ti, pero nunca la miraste.",
            f"{user}, la vida es como un código: si te atrancas, solo toca depurar.",
            f"{user}, no te preocupes si fallas, la caída es solo parte del proceso.",
            f"{user}, tu mayor error es no atreverte a soñar lo imposible.",
            f"{user}, si no te atreves a ser único, serás uno más del montón.",
            f"{user}, a veces, lo mejor que puedes hacer es desconectar un rato y reiniciar.",
            f"{user}, los que piensan que no pueden cambiar el mundo, deberían dejar de programar.",
            f"{user}, ¿quién dijo que lo imposible no se puede hacer? Asegúrate de demostrarlo.",
            f"{user}, no dejes que la desesperación sea tu puerto de destino, sigue navegando.",
            f"{user}, hoy no es solo otro día, es tu oportunidad para ser épico.",
            f"{user}, si encuentras un bug en tu vida, ¡ponle un break point!",
            f"{user}, solo hay una cosa más peligrosa que un hacker, y esa es la procrastinación.",
            f"{user}, cada error es solo una línea más de código hacia tu mejor versión.",
            f"{user}, el universo es un código en beta… y tú eres el debug.",
            f"{user}, lo que no te mata, te enseña, y lo que te enseña, te hace más fuerte.",
            f"{user}, el futuro no es un bug, es un feature que estás creando.",
            f"{user}, si no puedes con la situación, ¡reinicia tu mentalidad!",
            f"{user}, hoy es un buen día para tomar riesgos y romper algunas reglas.",
            f"{user}, cada día es una nueva oportunidad para crear tu código perfecto.",
            f"{user}, la respuesta está en la documentación. Si no la encuentras, ¡invéntala!",
            f"{user}, el caos y la creatividad suelen ir de la mano. No tengas miedo del desorden.",
            f"{user}, cada error en tu código te acerca un paso más a la perfección.",
            f"{user}, las estrellas no brillan sin oscuridad, igual que tus ideas brillarán después de la lluvia.",
            f"{user}, tu futuro no está escrito… pero sí está programado.",
            f"{user}, no eres un bug, eres un feature en construcción.",
            f"{user}, la vida es como un repo: cada vez que te caes, puedes hacer un rollback.",
            f"{user}, nunca subestimes la importancia de un buen plan de pruebas, ni en la vida.",
            f"{user}, cuando sientas que te has quedado sin ideas, recuerda: siempre puedes rebotar.",
            f"{user}, si no puedes solucionar el problema, ¡al menos haz que se vea interesante!",
            f"{user}, la verdad siempre sale a la luz… igual que ese error que se te escapó en producción.",
            f"{user}, cuando todo se derrumba, recuerda que el sistema siempre puede ser reiniciado.",
            f"{user}, todo lo que necesitas es una nueva perspectiva… y un poco de café.",
            f"{user}, todo en la vida tiene un paréntesis, incluso los problemas.",
            f"{user}, el código no miente, igual que las decisiones que tomas. ¡Que no te tiemble el pulso!",
            f"{user}, solo porque no veas el error, no significa que no esté ahí.",
            f"{user}, el éxito no es una línea recta, es más bien un conjunto de commits.",
            f"{user}, la creatividad es como el código: siempre puede ser mejorada.",
            f"{user}, nunca dudes de tu capacidad, aunque tu IDE diga lo contrario.",
            f"{user}, la vida, como tu código, es un trabajo en progreso.",
            f"{user}, los problemas siempre tienen solución… si sabes dónde buscar el bug.",
            f"{user}, no todo es negro o blanco, a veces hay un error en el sistema.",
            f"{user}, las ideas brillantes surgen de las sombras de los desafíos.",
            f"{user}, a veces solo hace falta un pequeño cambio para transformar todo el sistema.",
            f"{user}, tu próximo gran logro está a solo un push de distancia.",
        ]

        await ctx.send(random.choice(messages))
